# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d6916197dbe3d033c5bad63e0e9615e5d8d47affab3027418a35f96385c773669d445909a129a8fe295cb172e2083681334ba9e7515b0979a77d9bcf06a8a19

test:
  secret_key_base: d50dea509e983d22f169a904406d4062044dc3231873fea5b4c3a5f52b6ca11794cf7f42acf3baca07d41234e58be4a4f5a0d89c7597fe2eb4441362e7d6be4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
